spring:
  application:
    name: my-user-mgmt
  main:
    banner-mode: off

  liquibase:
    changeLog: "classpath:db/changelog/db.changelog-master.yml"

management:
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  endpoints:
    web:
      base-path: /admin
      exposure:
        include: "*"

springdoc:
  swagger-ui:
    path: /apidoc
  model-and-view-allowed: true
