version: "2.0"
services:
  db:
    image: "postgres:13-alpine"
    environment:
      - POSTGRES_USER=local_test
      - POSTGRES_PASSWORD=local_test
      - POSTGRES_DB=local_test
    ports:
      - "5432:5432"
